import { CKEditor } from "@ckeditor/ckeditor5-react";
import {
  ClassicEditor,
  AccessibilityHelp,
  Autoformat,
  AutoImage,
  Autosave,
  BlockQuote,
  Bold,
  Code,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  ImageBlock,
  ImageCaption,
  ImageInline,
  ImageInsert,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  ListProperties,
  MediaEmbed,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SelectAll,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  TodoList,
  Underline,
  Undo,
  SimpleUploadAdapter,
  Alignment,
  CodeBlock,
  SourceEditing,
} from "ckeditor5";

import "ckeditor5/ckeditor5.css";

export const EmailEditor: React.FC<{
  htmlContent: string;
  setHtmlContent: (content: string) => void;
  onEditorReady: (editor: any) => void;
  onDrop?: (e: React.DragEvent<HTMLDivElement>) => void;
}> = ({ htmlContent, setHtmlContent, onEditorReady, onDrop }) => {
  return (
    <div
      className="flex-1 flex flex-col content"
      onDrop={onDrop}
      onDragOver={(e) => e.preventDefault()}
    >
      <div className="flex-1 p-4 bg-white">
        <CKEditor
          editor={ClassicEditor}
          data={htmlContent}
          onReady={onEditorReady}
          onChange={(event: any, editor: any) => {
            const data = editor.getData();
            setHtmlContent(data);
          }}
          config={{
            licenseKey: "GPL",
            plugins: [
              AccessibilityHelp,
              Alignment,
              Autoformat,
              AutoImage,
              Autosave,
              BlockQuote,
              Bold,
              Code,
              CodeBlock,
              Essentials,
              FindAndReplace,
              FontBackgroundColor,
              FontColor,
              FontFamily,
              FontSize,
              GeneralHtmlSupport,
              Heading,
              Highlight,
              HorizontalLine,
              ImageBlock,
              ImageCaption,
              ImageInline,
              ImageInsert,
              ImageInsertViaUrl,
              ImageResize,
              ImageStyle,
              ImageTextAlternative,
              ImageToolbar,
              ImageUpload,
              Indent,
              IndentBlock,
              Italic,
              Link,
              LinkImage,
              List,
              ListProperties,
              MediaEmbed,
              Paragraph,
              PasteFromOffice,
              RemoveFormat,
              SelectAll,
              SimpleUploadAdapter,
              SourceEditing,
              SpecialCharacters,
              SpecialCharactersArrows,
              SpecialCharactersCurrency,
              SpecialCharactersEssentials,
              SpecialCharactersLatin,
              SpecialCharactersMathematical,
              SpecialCharactersText,
              Strikethrough,
              Subscript,
              Superscript,
              Table,
              TableCaption,
              TableCellProperties,
              TableColumnResize,
              TableProperties,
              TableToolbar,
              TextTransformation,
              TodoList,
              Underline,
              Undo,
            ],
            toolbar: {
              items: [
                "heading",
                "|",
                "fontSize",
                "fontFamily",
                "fontColor",
                "fontBackgroundColor",
                "|",
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "subscript",
                "superscript",
                "|",
                "alignment",
                "|",
                "numberedList",
                "bulletedList",
                "todoList",
                "|",
                "outdent",
                "indent",
                "|",
                "link",
                "insertImage",
                "insertTable",
                "mediaEmbed",
                "blockQuote",
                "codeBlock",
                "horizontalLine",
                "specialCharacters",
                "|",
                "findAndReplace",
                "selectAll",
                "|",
                "undo",
                "redo",
                "|",
                "sourceEditing",
              ],
              shouldNotGroupWhenFull: true,
            },
            fontSize: {
              options: [
                9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 22, 24, 26, 28, 30, 32,
                34, 36,
              ],
              supportAllValues: true,
            },
            fontFamily: {
              options: [
                "default",
                "Arial, Helvetica, sans-serif",
                "Georgia, serif",
                "Times New Roman, Times, serif",
                "Verdana, Geneva, sans-serif",
                "Trebuchet MS, Helvetica, sans-serif",
                "Courier New, Courier, monospace",
                "Impact, Charcoal, sans-serif",
              ],
              supportAllValues: true,
            },
            fontColor: {
              colors: [
                { color: "hsl(0, 0%, 0%)", label: "Black" },
                { color: "hsl(0, 0%, 30%)", label: "Dim grey" },
                { color: "hsl(0, 0%, 60%)", label: "Grey" },
                { color: "hsl(0, 0%, 90%)", label: "Light grey" },
                { color: "hsl(0, 0%, 100%)", label: "White" },
                { color: "hsl(0, 75%, 60%)", label: "Red" },
                { color: "hsl(30, 75%, 60%)", label: "Orange" },
                { color: "hsl(60, 75%, 60%)", label: "Yellow" },
                { color: "hsl(90, 75%, 60%)", label: "Light green" },
                { color: "hsl(120, 75%, 60%)", label: "Green" },
                { color: "hsl(150, 75%, 60%)", label: "Aquamarine" },
                { color: "hsl(180, 75%, 60%)", label: "Turquoise" },
                { color: "hsl(210, 75%, 60%)", label: "Light blue" },
                { color: "hsl(240, 75%, 60%)", label: "Blue" },
                { color: "hsl(270, 75%, 60%)", label: "Purple" },
              ],
            },
            fontBackgroundColor: {
              colors: [
                { color: "hsl(0, 0%, 100%)", label: "White" },
                { color: "hsl(0, 0%, 90%)", label: "Light grey" },
                { color: "hsl(0, 0%, 60%)", label: "Grey" },
                { color: "hsl(0, 0%, 30%)", label: "Dark grey" },
                { color: "hsl(0, 0%, 0%)", label: "Black" },
                { color: "hsl(0, 75%, 60%)", label: "Red" },
                { color: "hsl(30, 75%, 60%)", label: "Orange" },
                { color: "hsl(60, 75%, 60%)", label: "Yellow" },
                { color: "hsl(90, 75%, 60%)", label: "Light green" },
                { color: "hsl(120, 75%, 60%)", label: "Green" },
                { color: "hsl(180, 75%, 60%)", label: "Turquoise" },
                { color: "hsl(240, 75%, 60%)", label: "Blue" },
                { color: "hsl(270, 75%, 60%)", label: "Purple" },
              ],
            },
            heading: {
              options: [
                {
                  model: "paragraph",
                  title: "Paragraph",
                  class: "ck-heading_paragraph",
                },
                {
                  model: "heading1",
                  view: "h1",
                  title: "Heading 1",
                  class: "ck-heading_heading1",
                },
                {
                  model: "heading2",
                  view: "h2",
                  title: "Heading 2",
                  class: "ck-heading_heading2",
                },
                {
                  model: "heading3",
                  view: "h3",
                  title: "Heading 3",
                  class: "ck-heading_heading3",
                },
                {
                  model: "heading4",
                  view: "h4",
                  title: "Heading 4",
                  class: "ck-heading_heading4",
                },
              ],
            },
            alignment: {
              options: ["left", "center", "right", "justify"],
            },
            image: {
              toolbar: [
                "imageTextAlternative",
                "toggleImageCaption",
                "|",
                "imageStyle:inline",
                "imageStyle:wrapText",
                "imageStyle:breakText",
                "|",
                "resizeImage",
              ],
              resizeOptions: [
                {
                  name: "resizeImage:original",
                  label: "Original",
                  value: null,
                },
                {
                  name: "resizeImage:50",
                  label: "50%",
                  value: "50",
                },
                {
                  name: "resizeImage:75",
                  label: "75%",
                  value: "75",
                },
              ],
            },
            table: {
              contentToolbar: [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableCellProperties",
                "tableProperties",
              ],
            },
            link: {
              addTargetToExternalLinks: true,
              defaultProtocol: "https://",
            },
            list: {
              properties: {
                styles: true,
                startIndex: true,
                reversed: true,
              },
            },
            mediaEmbed: {
              previewsInData: true,
            },
            htmlSupport: {
              allow: [
                {
                  name: /.*/,
                  attributes: true,
                  classes: true,
                  styles: true,
                },
              ],
            },
            placeholder: "Start writing your email content here...",
          }}
        />
      </div>
    </div>
  );
};
